### ISSUE TITLE
RailsとReactの参考書のおすすめを教えて下さい。

### ISSUE THREAD

**Issue by taisuke-salty** [taisuke-salty/tenki_app#15]
RailsとReactの参考書のおすすめを教えて下さい。

**Comment by shoji-ippei** [comment]
@taisuke-salty 
遅くなりました！
ちょっと ￼Reactjs に関しては自分も知見が少ないので一般にググって出てくるものですが、 RoR は自分で読んだものからの選定です。

- Ruby
  - [チェリー本](https://www.amazon.co.jp/プロを目指す人のためのRuby入門-言語仕様からテスト駆動開発・デバッグ技法まで-Software-Design-plus-ebook/dp/B077Q8BXHC/ref=pd_aw_sim_3/356-4601646-0716557?_encoding=UTF8&pd_rd_i=B077Q8BXHC&pd_rd_r=c416f0a7-fae3-42d6-b7a7-f86289c5dc57&pd_rd_w=Y3Iu4&pd_rd_wg=yYmJ6&pf_rd_p=fb9268bc-1d8a-4b60-ac64-e9690d1d45f4&pf_rd_r=ZTMPTASW5A1Y4521CA2H&psc=1&refRID=ZTMPTASW5A1Y4521CA2H)
- Rails 
  - [黒本](https://www.amazon.co.jp/改訂2版-パーフェクトRuby-Rubyサポーターズ-ebook/dp/B071K5WM6P/ref=pd_aw_sim_4?_encoding=UTF8&pd_rd_i=B071K5WM6P&pd_rd_r=06b2df65-7fdf-4bc3-99a9-f6efe5e4104d&pd_rd_w=Yq6ZQ&pd_rd_wg=EPNrc&pf_rd_p=fb9268bc-1d8a-4b60-ac64-e9690d1d45f4&pf_rd_r=G00RE86AFTTAF46XTHT7&psc=1&refRID=C7GEJ4P7SQ8SZMW33C3V)
  - [実践ガイド](https://www.amazon.co.jp/dp/B082XXMVBK/)
  - [パーフェクトRubyonRails](https://www.amazon.co.jp/パーフェクト-Ruby-Rails-【増補改訂版】-すがわら-まさのり-ebook/dp/B08D3DW7LP/ref=pd_aw_sim_2/356-4601646-0716557?_encoding=UTF8&pd_rd_i=B08D3DW7LP&pd_rd_r=c416f0a7-fae3-42d6-b7a7-f86289c5dc57&pd_rd_w=Y3Iu4&pd_rd_wg=yYmJ6&pf_rd_p=fb9268bc-1d8a-4b60-ac64-e9690d1d45f4&pf_rd_r=ZTMPTASW5A1Y4521CA2H&psc=1&refRID=ZTMPTASW5A1Y4521CA2H)
- Reactjs
  - [React.js&Next.js超入門 第2版](https://www.amazon.co.jp/dp/4798063983/)
  - [あとはこういうサイトで共通に挙げられるのは無難なものかと。](https://freelifetech.com/react-books/)
