### ISSUE TITLE
html => erb? haml記法? への変換

### ISSUE THREAD

**Issue by taisuke-salty** [taisuke-salty/tenki_app#5]
以前、生のHTMLで書いたコードを転用しようと思っています。
とりあえず作成済みのHTMLファイルを、.html.erbとしてView適切な場所に保存しました。
<img>はerbの記法<%= %>に書き換えないとブラウザで画像を表示できない事がわかったので、
今、ひとつずつタグを書き換えています。

正直すべて手入力で書き換えるのが面倒なのですが、楽に書き換えられる方法はありますか？

**Comment by shoji-ippei** [comment]
https://regex101.com/

**Comment by shoji-ippei** [comment]
VScodeの置換と正規表現をうまく使うとできそうです。
正規表現は開発中に出てくるタイミングで少しずつ覚えていけば良いかと！
