### ISSUE TITLE
timezoneについて

### ISSUE THREAD

**Issue by taisuke-salty** [taisuke-salty/tenki_app#7]
以下のQiitaの記事を参照し、TimeWithZoneを用いて日時を操作しようと思います。
●RubyとRailsにおけるTime, Date, DateTime, TimeWithZoneの違い
https://qiita.com/jnchito/items/cae89ee43c30f5d6fa2c

＜質問1＞
アプリケーションで扱うデフォルトのTZをとりあえず日本に設定しようと思います。

上記記事の「Part 2. Railsの場合」「タイムゾーンの設定」には、「application.rb」に以下のコードを書くことが記載されています。
`config.time_zone = 'Tokyo'`
https://qiita.com/jnchito/items/cae89ee43c30f5d6fa2c#%E3%82%BF%E3%82%A4%E3%83%A0%E3%82%BE%E3%83%BC%E3%83%B3%E3%81%AE%E8%A8%AD%E5%AE%9A-1

config/application.rbに上記コードを追記し、
app/views/nikki/index.html.erbのBody内で以下の通りTZ名を表示させました。
`  <%= Time.zone.name %>`
結果は「UTC」で、日本の標準時間に設定できていませんでした。

＜質問2＞
以下のQiitaの記事で、タイムゾーンの設定について書いてあるのですが、具体的にどうしたらいいか相談したいです。
●Railsタイムゾーンまとめ
https://qiita.com/aosho235/items/a31b895ce46ee5d3b444

**Comment by taisuke-salty** [comment]
以下の修正にて解決しました。
・config.time_zone = 'Tokyo'を、下記＜※＞部分に記載する。
module TenkiApp
  class Application < Rails::Application
<※>
end

**Comment by shoji-ippei** [comment]
基本的に
- OS
- 言語ランタイム（今回はRuby）
- アプリケーション（今回はRails）
- DBその他

で独自に、かつ相互に影響しうるタイムゾーンを持っています。
厳密に言えば全てゾーンを合わせるのがよいですが、これもアプリの現状や性質から鑑みるに必要なところを必要になったタイミングで変えていく、という進め方で良いと思います！
